In [1]:

import numpy as np

def dct_matrix(n):
    D = np.zeros((n, n))
    for k in range(n):
        for i in range(n):
            if k == 0:
                D[k, i] = np.sqrt(1/n)
            else:
                D[k, i] = np.sqrt(2/n) * np.cos(np.pi*(2*i+1)*k/(2*n))
    return D

def to_q8_8(value):
    # Convert float to Q8.8 fixed point format.
    return int(round(value * 256)) & 0xFFFF


n = 8
D = dct_matrix(n)
# print(D)
q_matrix = [[to_q8_8(D[i,j]) for j in range(n)] for i in range(n)]
i=0
for row in q_matrix:
    for x in row:
        print("bram_D[{}] <= 16'h{:04X};".format(i,x),end=' ')
        i+=1


bram_D[0] <= 16'h005B; bram_D[1] <= 16'h005B; bram_D[2] <= 16'h005B; bram_D[3] <= 16'h005B; bram_D[4] <= 16'h005B; bram_D[5] <= 16'h005B; bram_D[6] <= 16'h005B; bram_D[7] <= 16'h005B; bram_D[8] <= 16'h007E; bram_D[9] <= 16'h006A; bram_D[10] <= 16'h0047; bram_D[11] <= 16'h0019; bram_D[12] <= 16'hFFE7; bram_D[13] <= 16'hFFB9; bram_D[14] <= 16'hFF96; bram_D[15] <= 16'hFF82; bram_D[16] <= 16'h0076; bram_D[17] <= 16'h0031; bram_D[18] <= 16'hFFCF; bram_D[19] <= 16'hFF8A; bram_D[20] <= 16'hFF8A; bram_D[21] <= 16'hFFCF; bram_D[22] <= 16'h0031; bram_D[23] <= 16'h0076; bram_D[24] <= 16'h006A; bram_D[25] <= 16'hFFE7; bram_D[26] <= 16'hFF82; bram_D[27] <= 16'hFFB9; bram_D[28] <= 16'h0047; bram_D[29] <= 16'h007E; bram_D[30] <= 16'h0019; bram_D[31] <= 16'hFF96; bram_D[32] <= 16'h005B; bram_D[33] <= 16'hFFA5; bram_D[34] <= 16'hFFA5; bram_D[35] <= 16'h005B; bram_D[36] <= 16'h005B; bram_D[37] <= 16'hFFA5; bram_D[38] <= 16'hFFA5; bram_D[39] <= 16'h005B; bram_D[40] <= 16'h0047; bram_D[41] <= 16'hFF82; br

In [ ]:
test = np.ones((8,8))
sol = D@test@D.T
ans = [[to_q8_8(sol[i,j]) for j in range(n)] for i in range(n)]
for row in ans:
        print(" ".join("{:04X}".format(x) for x in row))

0800 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000


In [57]:
def q8_8_to_float(value: int) -> float:
    # Interpret the 16-bit value as signed
    if value & 0x8000:  # If sign bit is set
        value -= 0x10000  # Two's complement adjustment
    return value / 256.0

# Example input
hex_input = 0x3200
result = q8_8_to_float(hex_input)
result


50.0

In [37]:
import cv2
test = cv2.imread('img.png',cv2.IMREAD_GRAYSCALE)-128
sol = D@test@D.T
ans = [[to_q8_8(sol[i,j]) for j in range(n)] for i in range(n)]
for row in ans:
    print(" ".join("{:04X}".format(x) for x in row))


FA40 FFCB FE8F FFB0 FFC0 0005 FFC9 0251
0059 006D FF75 FF9D 0012 FFAC 008B 006D
FF36 0017 006D 0042 0023 FF9E 002D FF8C
004B FFDD FFF2 0013 FFCE FFED FFF2 0094
FFC0 005D FFDD FFBC 0040 FFF2 0054 FF75
0032 FFEC FFBC 0013 004B 0013 FFBC FFDD
000E FFF6 002D FFE5 FFAC 0029 0013 0030
0012 FF93 005D 0054 FFA7 001D FFA3 006D


In [60]:
import numpy as np
from scipy.fftpack import dct, idct

def dct2(matrix):
    """Compute the 2D DCT (type-II) with orthonormal normalization."""
    return dct(dct(matrix, axis=0, norm='ortho'), axis=1, norm='ortho')

def idct2(matrix):
    """Compute the 2D inverse DCT (type-II) with orthonormal normalization."""
    return idct(idct(matrix, axis=0, norm='ortho'), axis=1, norm='ortho')

def to_q8_8(val):
    """
    Convert a floating-point value to Q8.8 fixed-point format,
    represented as a signed 16-bit integer.
    """
    return np.int16(np.round(val * 256))

def q8_8_format(matrix):
    """
    Convert a 2D numpy array of floating-point numbers to a string
    of Q8.8 fixed-point hexadecimal values.
    """
    q8_8_matrix = np.empty_like(matrix, dtype=np.int16)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            q8_8_matrix[i, j] = to_q8_8(matrix[i, j])
    # Build a multi-line hex string.
    lines = []
    for row in q8_8_matrix:
        # Cast each element to a Python int to avoid overflow issues
        line = " ".join("{:04X}".format(int(x) & 0xFFFF) for x in row)
        lines.append(line)
    return "\n".join(lines)

def parse_q8_8_str(q8_8_str):
    """
    Parse a multi-line string of Q8.8 hexadecimal values into an 8x8 float matrix.
    """
    tokens = q8_8_str.split()
    coeffs = []
    for token in tokens:
        val = int(token, 16)
        # Convert from unsigned to signed (16-bit two's complement)
        if val & 0x8000:
            val -= 0x10000
        coeffs.append(val)
    coeffs = np.array(coeffs, dtype=np.int16).reshape((8, 8))
    # Convert from Q8.8 fixed-point to float.
    return coeffs.astype(np.float32) / 256.0

def compute_rmse_psnr(original, reconstructed):
    """
    Compute RMSE and PSNR between the original and reconstructed matrices.
    """
    mse = np.mean((original - reconstructed) ** 2)
    rmse = np.sqrt(mse)
    if mse == 0:
        psnr = float('inf')
    else:
        psnr = 20 * np.log10(255.0 / rmse)
    return rmse, psnr

def generate_valid_matrix():
    """
    Generate a random 8x8 matrix with values 0 to 255 whose forward DCT 
    coefficients all lie within the range [-127, 127]. If not, try again.
    """
    while True:
        M = np.random.randint(-64, 64, (8, 8)).astype(np.float32)
        dct_coeffs = dct2(M)
        if np.all(dct_coeffs >= -127) and np.all(dct_coeffs <= 127):
            return M, dct_coeffs

def main():
    np.random.seed(2308)  # For reproducibility
    
    # Step 1: Generate a valid random 8x8 matrix.
    original_matrix, dct_coeffs = generate_valid_matrix()
    print("Original 8x8 Matrix (values 0-255):")
    print(original_matrix)
    print()
    cnt = 0
    for i in range(8):
        for j in range(8):
            print(f"dut.bram_X[{cnt}] = 16'h{int(to_q8_8(original_matrix[i][j]))& 0xFFFF:04X};",end=' ')
            cnt+=1
    print()
    print()
    
    # Step 2: Compute its forward 2D DCT (already done in generate_valid_matrix) 
    # and print the coefficients (float format).
    print("DCT Coefficients (float) in range [-127, 127]:")
    print(np.round(dct_coeffs, 2))
    print()
    
    # Step 3: Convert the DCT coefficients to Q8.8 fixed-point hexadecimal format.
    q8_8_str = q8_8_format(dct_coeffs)
    print("DCT Coefficients in Q8.8 fixed-point format (hex):")
    print(q8_8_str)
    print()
    
    # Step 4: Simulate user input by using the Q8.8 string and parse it.
    user_input = """0a1b 2f72 f9db ed93 f014 debe 21c1 28e2 
37a7 00c5 347e e240 f040 e13b e2b7 a81f 
0b4f 0219 3ce7 414d ce0f 24a2 fc48 e05e 
eed0 c6fd e1ae 1522 3364 fbc4 15fe 1d43 
5d81 f59c 20d2 9f97 10ee e629 e8f0 2214 
39b3 2620 c593 0d4a 39c2 f122 fb22 de46 
f2a3 2448 0004 bdff c2eb 2161 da42 f48a 
f171 f836 f35c 0676 d3e2 0b6f 0378 1604""" # In practice, this string could be provided by the user.
    parsed_dct = parse_q8_8_str(user_input)
    
    # Reconstruct the matrix using the inverse 2D DCT.
    reconstructed_matrix = idct2(parsed_dct)
    print("Reconstructed 8x8 Matrix:")
    print(np.round(reconstructed_matrix, 2))
    print()
    
    # Step 5: Compute RMSE and PSNR between the original and reconstructed matrices.
    rmse, psnr = compute_rmse_psnr(original_matrix, reconstructed_matrix)
    print("RMSE: {:.4f}".format(rmse))
    print("PSNR: {:.2f} dB".format(psnr))
    
main()


Original 8x8 Matrix (values 0-255):
[[ 22.  63.  18.  24.  -5.  17.  19.  50.]
 [ 24.   9. -38. -53. -36.  39. -10.   7.]
 [-19.  63.  36.   6. -55.  -6. -11. -54.]
 [ 16.  50.  46.  57.  63. -30. -52.  61.]
 [-39. -35.  59. -42.  44. -39.  -3.  34.]
 [-24. -55.  11. -14.  12. -26. -33. -43.]
 [ 35. -64. -15. -18.  63.  44. -44. -61.]
 [ 19.  22.  57. -44. -34. -27.  38. -19.]]

dut.bram_X[0] = 16'h1600; dut.bram_X[1] = 16'h3F00; dut.bram_X[2] = 16'h1200; dut.bram_X[3] = 16'h1800; dut.bram_X[4] = 16'hFB00; dut.bram_X[5] = 16'h1100; dut.bram_X[6] = 16'h1300; dut.bram_X[7] = 16'h3200; dut.bram_X[8] = 16'h1800; dut.bram_X[9] = 16'h0900; dut.bram_X[10] = 16'hDA00; dut.bram_X[11] = 16'hCB00; dut.bram_X[12] = 16'hDC00; dut.bram_X[13] = 16'h2700; dut.bram_X[14] = 16'hF600; dut.bram_X[15] = 16'h0700; dut.bram_X[16] = 16'hED00; dut.bram_X[17] = 16'h3F00; dut.bram_X[18] = 16'h2400; dut.bram_X[19] = 16'h0600; dut.bram_X[20] = 16'hC900; dut.bram_X[21] = 16'hFA00; dut.bram_X[22] = 16'hF500; dut.bra

11.5

In [65]:

import numpy as np

def dct_matrix(n):
    D = np.zeros((n, n))
    for k in range(n):
        for i in range(n):
            if k == 0:
                D[k, i] = np.sqrt(1/n)
            else:
                D[k, i] = np.sqrt(2/n) * np.cos(np.pi*(2*i+1)*k/(2*n))
    return D

def to_q11_5(value):
    # Convert float to Q8.8 fixed point format.
    return int(round(value * 32)) & 0xFFFF


n = 8
D = dct_matrix(n)
# print(D)
q_matrix = [[to_q11_5(D[i,j]) for j in range(n)] for i in range(n)]
i=0
for row in q_matrix:
    for x in row:
        print("bram_D[{}] <= 16'h{:04X};".format(i,x),end=' ')
        i+=1


bram_D[0] <= 16'h000B; bram_D[1] <= 16'h000B; bram_D[2] <= 16'h000B; bram_D[3] <= 16'h000B; bram_D[4] <= 16'h000B; bram_D[5] <= 16'h000B; bram_D[6] <= 16'h000B; bram_D[7] <= 16'h000B; bram_D[8] <= 16'h0010; bram_D[9] <= 16'h000D; bram_D[10] <= 16'h0009; bram_D[11] <= 16'h0003; bram_D[12] <= 16'hFFFD; bram_D[13] <= 16'hFFF7; bram_D[14] <= 16'hFFF3; bram_D[15] <= 16'hFFF0; bram_D[16] <= 16'h000F; bram_D[17] <= 16'h0006; bram_D[18] <= 16'hFFFA; bram_D[19] <= 16'hFFF1; bram_D[20] <= 16'hFFF1; bram_D[21] <= 16'hFFFA; bram_D[22] <= 16'h0006; bram_D[23] <= 16'h000F; bram_D[24] <= 16'h000D; bram_D[25] <= 16'hFFFD; bram_D[26] <= 16'hFFF0; bram_D[27] <= 16'hFFF7; bram_D[28] <= 16'h0009; bram_D[29] <= 16'h0010; bram_D[30] <= 16'h0003; bram_D[31] <= 16'hFFF3; bram_D[32] <= 16'h000B; bram_D[33] <= 16'hFFF5; bram_D[34] <= 16'hFFF5; bram_D[35] <= 16'h000B; bram_D[36] <= 16'h000B; bram_D[37] <= 16'hFFF5; bram_D[38] <= 16'hFFF5; bram_D[39] <= 16'h000B; bram_D[40] <= 16'h0009; bram_D[41] <= 16'hFFF0; br

In [3]:
import numpy as np
from scipy.fftpack import dct, idct

def dct2(matrix):
    """Compute the 2D DCT (type-II) with orthonormal normalization."""
    return dct(dct(matrix, axis=0, norm='ortho'), axis=1, norm='ortho')

def idct2(matrix):
    """Compute the 2D inverse DCT (type-II) with orthonormal normalization."""
    return idct(idct(matrix, axis=0, norm='ortho'), axis=1, norm='ortho')

def to_q11_5(val):
    """
    Convert a floating-point value to Q11.5 fixed-point format,
    represented as a signed 16-bit integer.
    """
    # Multiply by 2^5 = 32
    return np.int16(np.round(val * 32))

def q11_5_format(matrix):
    """
    Convert a 2D numpy array of floating-point numbers to a string
    of Q11.5 fixed-point hexadecimal values.
    """
    q11_5_matrix = np.empty_like(matrix, dtype=np.int16)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            q11_5_matrix[i, j] = to_q11_5(matrix[i, j])
    # Build a multi-line hex string.
    lines = []
    for row in q11_5_matrix:
        # Cast each element to Python int to avoid overflow issues
        line = " ".join("{:04X}".format(int(x) & 0xFFFF) for x in row)
        lines.append(line)
    return "\n".join(lines)

def parse_q11_5_str(q11_5_str):
    """
    Parse a multi-line string of Q11.5 hexadecimal values into an 8x8 float matrix.
    """
    tokens = q11_5_str.split()
    coeffs = []
    for token in tokens:
        val = int(token, 16)
        # Convert from unsigned to signed (16-bit two's complement)
        if val & 0x8000:
            val -= 0x10000
        coeffs.append(val)
    coeffs = np.array(coeffs, dtype=np.int16).reshape((8, 8))
    # Convert from Q11.5 fixed-point to float (divide by 32)
    return coeffs.astype(np.float32) / 32.0

def compute_rmse_psnr(original, reconstructed):
    """
    Compute RMSE and PSNR between the original and reconstructed matrices.
    """
    mse = np.mean((original - reconstructed) ** 2)
    rmse = np.sqrt(mse)
    if mse == 0:
        psnr = float('inf')
    else:
        psnr = 20 * np.log10(255.0 / rmse)
    return rmse, psnr

def generate_valid_matrix():
    """
    Generate a random 8x8 matrix with values in the range [-64, 63] whose forward DCT 
    coefficients all lie within the range [-127, 127]. If not, try again.
    """
    while True:
        M = np.random.randint(-127,127, (8, 8)).astype(np.float32)
        dct_coeffs = dct2(M)
        return M, dct_coeffs

def main():
    np.random.seed(123)  # For reproducibility
    
    # Step 1: Generate a valid random 8x8 matrix.
    original_matrix, dct_coeffs = generate_valid_matrix()
    print("Original 8x8 Matrix (values in range [-64, 63]):")
    print(original_matrix)
    print()
    
    # Print each element of the original matrix in Q11.5 format
    cnt = 0
    for i in range(8):
        for j in range(8):
            print(f"dut.bram_X[{cnt}] = 16'h{int(to_q11_5(original_matrix[i][j])) & 0xFFFF:04X};", end=' ')
            cnt += 1
    print("\n")
    
    # Step 2: Print the DCT coefficients (float format) which are in range [-127, 127].
    print("DCT Coefficients (float) in range [-127, 127]:")
    print(np.round(dct_coeffs, 2))
    print()
    
    # Step 3: Convert the DCT coefficients to Q11.5 fixed-point hexadecimal format.
    q11_5_str = q11_5_format(dct_coeffs)
    print("DCT Coefficients in Q11.5 fixed-point format (hex):")
    print(q11_5_str)
    print()
    
    # Step 4: Simulate user input by using a provided Q11.5 hex string and parse it.
    user_input = """f8a8 0169 fc6d fae7 0beb f30d 039e f905 
00dd fdf5 ea76 0fa7 05ed 03bd f2c2 f960 
021a fe98 f81b fd24 fd27 0370 01c3 f140 
037e 0234 0d9d 029e 0372 039b 1329 f69c 
f7be 0776 0547 fe9a fc5a fbf2 0443 fca1 
037d 06dc f4b6 fe08 f4f1 f92e 0483 fc96 
fe7b ff73 ffa0 068b fc20 03cf f8ba fbb1 
f828 f01e 04cf 01dd 08a1 0946 0db3 fee9"""
    # In practice, the user would supply the above string.
    parsed_dct = parse_q11_5_str(user_input)
    
    # Reconstruct the matrix using the inverse 2D DCT.
    reconstructed_matrix = idct2(parsed_dct)
    print("Reconstructed 8x8 Matrix:")
    print(np.round(reconstructed_matrix, 2))
    print()
    
    # Step 5: Compute RMSE and PSNR between the original and reconstructed matrices.
    rmse, psnr = compute_rmse_psnr(original_matrix, reconstructed_matrix)
    print("RMSE: {:.4f}".format(rmse))
    print("PSNR: {:.2f} dB".format(psnr))
    
if __name__ == "__main__":
    main()


Original 8x8 Matrix (values in range [-64, 63]):
[[ -18.   -1.  -61.   93.  -29.  103. -110.  -44.]
 [ -21.   -4.  -70.   87.   98.  -31.  -14.   -1.]
 [ -80.  -54.  -95.   47.   97.  -16.   26.  -44.]
 [ -49.  126.   37.  -31.   81.  -59.  -78.  -72.]
 [  68. -125.  -43.  -88.  -61.  -43.  -80.  121.]
 [  62.   49.    8.  -22.  -28.   -3.  -35.   53.]
 [ -25.  -30.   86.   -9.  -33.   28.  -93.   98.]
 [ -51.   41.    4.  -21.  -58.  -63.  -52.   35.]]

dut.bram_X[0] = 16'hFDC0; dut.bram_X[1] = 16'hFFE0; dut.bram_X[2] = 16'hF860; dut.bram_X[3] = 16'h0BA0; dut.bram_X[4] = 16'hFC60; dut.bram_X[5] = 16'h0CE0; dut.bram_X[6] = 16'hF240; dut.bram_X[7] = 16'hFA80; dut.bram_X[8] = 16'hFD60; dut.bram_X[9] = 16'hFF80; dut.bram_X[10] = 16'hF740; dut.bram_X[11] = 16'h0AE0; dut.bram_X[12] = 16'h0C40; dut.bram_X[13] = 16'hFC20; dut.bram_X[14] = 16'hFE40; dut.bram_X[15] = 16'hFFE0; dut.bram_X[16] = 16'hF600; dut.bram_X[17] = 16'hF940; dut.bram_X[18] = 16'hF420; dut.bram_X[19] = 16'h05E0; dut.bram_X[